---
title: "instantiate"
description: |
  start the day
date: "updated `r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r get data}
library(tidyverse)
library(dontpanic)
library(gt)

instantiate <- read_rds("data/instantiate.rds")

```


## instantiate

```{r}

instantiate %>% 
  gt() 

```


## categories

$\overline o$ | time dependent | anytime 
-|-|- 
research | $\varphi$ (postdoc work, manuscripts w due dates) | $\theta$ (collaborations, reading) 
not research | $\psi$ (busywork) | $\pi$ (exercise, housework)


## things to do next

[Go to Weekend tasks](#weekend)

```{r}
tasks <- read_rds("data/tasks.rds")

tasks %>% 
  filter(status == "star") %>%
  select(-weekend) %>% 
  gt(
    groupname_col = "category"
  ) %>% 
  opt_row_striping() %>% 
  tab_options(
    row_group.background.color = "lightgrey"
  ) 

```

## weekend

```{r}
tasks %>% 
  filter(status == "star") %>% 
  filter(weekend) %>% 
  select(-weekend) %>% 
  gt(
    groupname_col = "category"
    
  ) %>% 
  opt_row_striping() %>% 
  tab_options(
    row_group.background.color = "lightgrey"
  )


```


